# Generated by Django 2.2.6 on 2020-02-06 07:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('p_library', '0002_userprofile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
